apiVersion: v1
kind: Service
metadata:
  labels:
    app: poke-server
  name: poke-server
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: poke-server